Place.create!([
  {name: "Secretaria de Graduação"},
  {name: "Secretaria da Direção"},
  {name: "Biblioteca"}
])
Type.create!([
  {name: "Solicitação de Equipamento"},
  {name: "Revisão de Menção"},
  {name: "Compravante de Matrícula"},
  {name: "Lista de Presença"},
  {name: "Afastamento"},
  {name: "Documentação"},
  {name: "Material Escritório"},
  {name: "Viagens"},
  {name: "Diárias"},
  {name: "Passagens"},
  {name: "Prestação de Contas"},
  {name: "Inscrições"},
  {name: "Crachá"},
  {name: "Concursos"},
  {name: "Recursos"},
  {name: "Aproveitamento de Estudos"},
  {name: "Ementa"},
  {name: "Lista de Ofertas"},
  {name: "Carimbar Documentos"},
  {name: "Processos"},
  {name: "Frequência"},
  {name: "Marcação de Férias"},
  {name: "Atendimento Telefônico"},
  {name: "Impressão de Provas"},
  {name: "Encadernação"},
  {name: "Agendar Reunião"},
  {name: "Entregar Documentos Diversos"},
  {name: "Buscar Documentos Diversos"},
  {name: "Logística de Realização"},
  {name: "Pedido de Informação"},
  {name: "Assinatura de Documentos"},
  {name: "Pesquisa no SIGRA"},
  {name: "Pesquisa no UNBDOC"},
  {name: "Realizar Ligação"},
  {name: "Reserva de Sala"},
  {name: "Solicitação de Material"},
  {name: "Solicitar Atendimento do prof. Coordenador Geral"},
  {name: "Solicitar Atendimento do prof. Diretor"},
  {name: "Solicitar Atendimento do prof. Vice-Diretor"},
  {name: "Solicitar Impressão"},
  {name: "Solicitar Formulários"},
  {name: "Solicitar Xerox"},
  {name: "Empréstimo de Materiais Bibliográficos"},
  {name: "Renovação de Materiais Bibliográficos"},
  {name: "Devolução de Materiais Bibliográficos"},
  {name: "Reserva de Materiais Bibliográficos"},
  {name: "Renovação de Cadastro de Usuários"},
  {name: "Emissão de Multa"},
  {name: "Emissão de Nada Consta"},
  {name: "Pagamento de Multa"},
  {name: "Resolução de Pendências de Usuários"},
  {name: "Solicitação de Pedidos do COMUT"},
  {name: "Publicidade de Novas Aquisições"},
  {name: "Guarda de materiais perdidos"},
  {name: "Auxílio em pesquisas em bases de dados e bibliotecas digitais"},
  {name: "Realização de pesquisas no catálogo online"},
  {name: "Emissão de etiquetas, carimbagem, papeletas e fitas magnéticas para materiais bibliográficos"},
  {name: "Empréstimo de computadores"},
  {name: "Auxílio estante"},
  {name: "Prestação de informações de interesse aos usuários e visitantes"},
  {name: "Verificação de sugestões e pedidos de materiais bibliográficos para aquisição"},
  {name: "Recebimento e seleção de doações"},
  {name: "Envio de relatórios de materiais bibliográficos"},
  {name: "Declaração"}
])
