require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ComunidadesController do

  # This should return the minimal set of attributes required to create a valid
  # Comunidade. As you add validations to Comunidade, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { :name => "Alessandro", :identificacao => "02919594150" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ComunidadesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all comunidades as @comunidades" do
      comunidade = Comunidade.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:comunidades)).to eq([comunidade])
    end
  end

  describe "GET show" do
    it "assigns the requested comunidade as @comunidade" do
      comunidade = Comunidade.create! valid_attributes
      get :show, {:id => comunidade.to_param}, valid_session
      expect(assigns(:comunidade)).to eq(comunidade)
    end
  end

  describe "GET new" do
    it "assigns a new comunidade as @comunidade" do
      get :new, {}, valid_session
      expect(assigns(:comunidade)).to be_a_new(Comunidade)
    end
  end

  describe "GET edit" do
    it "assigns the requested comunidade as @comunidade" do
      comunidade = Comunidade.create! valid_attributes
      get :edit, {:id => comunidade.to_param}, valid_session
      expect(assigns(:comunidade)).to eq(comunidade)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Comunidade" do
        expect {
          post :create, {:comunidade => valid_attributes}, valid_session
        }.to change(Comunidade, :count).by(1)
      end

      it "assigns a newly created comunidade as @comunidade" do
        post :create, {:comunidade => valid_attributes}, valid_session
        expect(assigns(:comunidade)).to be_a(Comunidade)
        expect(assigns(:comunidade)).to be_persisted
      end

      it "redirects to the created comunidade" do
        post :create, {:comunidade => valid_attributes}, valid_session
        expect(response).to redirect_to(comunidades_path)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved comunidade as @comunidade" do
        # Trigger the behavior that occurs when invalid params are submitted
        Comunidade.any_instance.stub(:save).and_return(false)
        post :create, {:comunidade => {  }}, valid_session
        expect(assigns(:comunidade)).to be_a_new(Comunidade)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Comunidade.any_instance.stub(:save).and_return(false)
        post :create, {:comunidade => {  }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested comunidade" do
        comunidade = Comunidade.create! valid_attributes
        # Assuming there are no other comunidades in the database, this
        # specifies that the Comunidade created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Comunidade).to receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => comunidade.to_param, :comunidade => { "these" => "params" }}, valid_session
      end

      it "assigns the requested comunidade as @comunidade" do
        comunidade = Comunidade.create! valid_attributes
        put :update, {:id => comunidade.to_param, :comunidade => valid_attributes}, valid_session
        expect(assigns(:comunidade)).to eq(comunidade)
      end

      it "redirects to the comunidade" do
        comunidade = Comunidade.create! valid_attributes
        put :update, {:id => comunidade.to_param, :comunidade => valid_attributes}, valid_session
        expect(response).to redirect_to(comunidades_path)
      end
    end

    describe "with invalid params" do
      it "assigns the comunidade as @comunidade" do
        comunidade = Comunidade.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Comunidade.any_instance.stub(:save).and_return(false)
        put :update, {:id => comunidade.to_param, :comunidade => {  }}, valid_session
        expect(assigns(:comunidade)).to eq(comunidade)
      end

      it "re-renders the 'edit' template" do
        comunidade = Comunidade.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Comunidade.any_instance.stub(:save).and_return(false)
        put :update, {:id => comunidade.to_param, :comunidade => {  }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested comunidade" do
      comunidade = Comunidade.create! valid_attributes
      expect {
        delete :destroy, {:id => comunidade.to_param}, valid_session
      }.to change(Comunidade, :count).by(-1)
    end

    it "redirects to the comunidades list" do
      comunidade = Comunidade.create! valid_attributes
      delete :destroy, {:id => comunidade.to_param}, valid_session
      expect(response).to redirect_to(comunidades_url)
    end
  end

end
